---
- hosts: clients
  roles:
      - role: ansible-role-aws-s3
        mode: get
        src: s3://test-bucket/test-file.txt
        dest: /tmp/test.txt
        aws_endpoint_url: http://minio:9000
        aws_region: us-east-1
        aws_access_key: AKIAIOSFODNN7EXAMPLE
        aws_secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
